### ISSUE TITLE
Change FR homepage 'see less' buttons in main body copy to Réduire (from Réduir)

### ISSUE THREAD

**Issue by adambard1** [rayrshah/midisWP#11]
Change the spelling of the see less button for the on the FR home page value propositions from Réduir to Réduire.

example:
WordPress
<img width="1220" alt="Screen Shot 2021-06-18 at 14 42 20" src="https://user-images.githubusercontent.com/13530245/122570289-9b1c1200-d019-11eb-9d6e-e0dba1fe2c18.png">

Current
<img width="1230" alt="Screen Shot 2021-06-18 at 14 44 51" src="https://user-images.githubusercontent.com/13530245/122570589-e1717100-d019-11eb-8f28-8eacea735bb0.png">

**Comment by ajazmi** [comment]
@adambard1 Updated
