### ISSUE TITLE
Copy edit on FR Homepage "Savoir" not "Savior"

### ISSUE THREAD

**Issue by adambard1** [rayrshah/midisWP#12]
- [ ] Fix this misspelling.
- Suggest waiting till the backend access is shared, then we can test the ability to copyedit to fix this
- This was an issue on the current site that I have edited today, so it was not created by the Development, but needs to be fixed before launch
Current 
<img width="1192" alt="Screen Shot 2021-06-18 at 15 03 21" src="https://user-images.githubusercontent.com/13530245/122573800-f996bf80-d01c-11eb-8191-4d8e97f2586a.png">

WordPress
<img width="661" alt="Screen Shot 2021-06-18 at 15 02 32" src="https://user-images.githubusercontent.com/13530245/122573839-02879100-d01d-11eb-81b0-1ae2580856dc.png">

**Comment by adambard1** [comment]
@ajazmi let us fix this in the CMS when you share the credentials

**Comment by ajazmi** [comment]
@adambard1 Copy updated on wordpress.
