### ISSUE TITLE
Fix FR Homepage 'Article Recents' hyperlink

### ISSUE THREAD

**Issue by adambard1** [rayrshah/midisWP#13]
FR Homepage 'Articles récents' hyperlink produces an error, it takes you to https://www.midisgroup.com/fr/news/ it should take you to https://www.midisgroup.com/fr/actualites/
<img width="431" alt="Screen Shot 2021-06-18 at 15 12 16" src="https://user-images.githubusercontent.com/13530245/122574467-acffb400-d01d-11eb-8e3b-c654adbe483b.png">

- [ ] amend URL hyperlink forArticles récents to https://www.midisgroup.com/fr/actualites/

**Comment by adambard1** [comment]
@ajazmi

**Comment by ajazmi** [comment]
@adambard1 Fixed.

**Comment by adambard1** [comment]
Thinking about this, @ajazmi we presumably want the links to go to our WordPress site? I had not thought of it previously, and just put in the current site given the broken link was pointing us to the current site.

- [ ] amend this link to: https://midisgroup.thinkdesign.com/fr/actualites/

**Comment by ajazmi** [comment]
@adambard1 Ideally, it should go to https://midisgroup.thinkdesign.com/fr/actualites/ for FR and https://midisgroup.thinkdesign.com/news/ for EN. I have updated link for both. These link will be changed to live domain when we push site live.
