### ISSUE TITLE
EN Footer menu copy edit "Technology-Partners" remove the hyphen

### ISSUE THREAD

**Issue by adambard1** [rayrshah/midisWP#14]
- [x] Change footer menu copy to "Technology Partners"
Current
<img width="463" alt="Screen Shot 2021-06-18 at 16 19 27" src="https://user-images.githubusercontent.com/13530245/122583281-0ddfba00-d027-11eb-8bfa-b86035b980f3.png">
WordPress
<img width="451" alt="Screen Shot 2021-06-18 at 16 15 27" src="https://user-images.githubusercontent.com/13530245/122583385-28b22e80-d027-11eb-9ea3-0d29984cdcb7.png">

**Comment by adambard1** [comment]
@ajazmi this looks like another one we can fix when testing the CMS

**Comment by ajazmi** [comment]
@adambard1 Fixed
