### ISSUE TITLE
Fix Site and Power link on Channels page

### ISSUE THREAD

**Issue by adambard1** [rayrshah/midisWP#15]
the link https://midisgroup.thinkdesign.com/technology-partners/#site-and-power does not take you to the site and power tech partners

source link on https://midisgroup.thinkdesign.com/channels/
<img width="364" alt="Screen Shot 2021-06-18 at 18 00 22" src="https://user-images.githubusercontent.com/13530245/122594601-379fdd80-d035-11eb-9a97-32cd97f262e5.png">

- [x] Fix the link/bookmark

WordPress
<img width="1280" alt="Screen Shot 2021-06-18 at 16 39 37" src="https://user-images.githubusercontent.com/13530245/122585981-14bbfc00-d02a-11eb-9f58-060eefc9c0e1.png">

Current
<img width="1280" alt="Screen Shot 2021-06-18 at 16 42 00" src="https://user-images.githubusercontent.com/13530245/122586072-34ebbb00-d02a-11eb-8de0-4213fae07745.png">

**Comment by adambard1** [comment]
@ajazmi

**Comment by ajazmi** [comment]
@adambard1 Fixed link on en and fr channel pages.
