### ISSUE TITLE
Fix Software Solutions and Professional Services Technology partners hyperlink on Channel page

### ISSUE THREAD

**Issue by adambard1** [rayrshah/midisWP#16]
This link and bookmark https://midisgroup.thinkdesign.com/technology-partners/#software-solutions-and-professional-services does not take you to the right place on the technology partners page

source link on https://midisgroup.thinkdesign.com/channels/
<img width="441" alt="Screen Shot 2021-06-18 at 17 56 25" src="https://user-images.githubusercontent.com/13530245/122594125-99ac1300-d034-11eb-9ed8-1c870a0c3ac6.png">

- [x] Fix the link/bookmark

Wordpress
<img width="1280" alt="Screen Shot 2021-06-18 at 16 45 50" src="https://user-images.githubusercontent.com/13530245/122586538-d115c200-d02a-11eb-8d1f-e48aa1d9de9f.png">

Current
<img width="1280" alt="Screen Shot 2021-06-18 at 16 46 01" src="https://user-images.githubusercontent.com/13530245/122586508-c4916980-d02a-11eb-9f75-8160b9cb5311.png">

**Comment by adambard1** [comment]
@ajazmi

**Comment by ajazmi** [comment]
@adambard1 Fixed
