### ISSUE TITLE
Fix Partenaire de distribution hyperlink on FR Secteurs d'Activités page

### ISSUE THREAD

**Issue by adambard1** [rayrshah/midisWP#17]
The link https://midisgroup.thinkdesign.com/fr/secteurs/#distribution does not take you to the right place

source link on https://midisgroup.thinkdesign.com/fr/secteurs/:
<img width="259" alt="Screen Shot 2021-06-18 at 17 55 01" src="https://user-images.githubusercontent.com/13530245/122593971-67021a80-d034-11eb-94f3-1d3bb0349bab.png">

- [x] Fix the link/bookmark

WordPress
<img width="1280" alt="Screen Shot 2021-06-18 at 17 50 57" src="https://user-images.githubusercontent.com/13530245/122593564-d62b3f00-d033-11eb-9975-86eb5c6e037b.png">

Current (links to FR Tech distribution partners)
<img width="1280" alt="Screen Shot 2021-06-18 at 17 51 26" src="https://user-images.githubusercontent.com/13530245/122593619-e8a57880-d033-11eb-8c7d-0fe82b115217.png">

**Comment by adambard1** [comment]
@ajazmi

**Comment by ajazmi** [comment]
@adambard1 Fixed.
