### ISSUE TITLE
Fix Partenaires de Commerce de Détail link on FR Secteurs d'Activités page

### ISSUE THREAD

**Issue by adambard1** [rayrshah/midisWP#18]
The link https://midisgroup.thinkdesign.com/fr/partenaires-techonologiques/#retail does not go to the right content

Source link on https://midisgroup.thinkdesign.com/fr/secteurs/
<img width="355" alt="Screen Shot 2021-06-18 at 18 04 27" src="https://user-images.githubusercontent.com/13530245/122594950-b85ed980-d035-11eb-930f-ea699f47eb18.png">

- [x] fix the link/bookmark

WordPress site
<img width="1280" alt="Screen Shot 2021-06-18 at 19 25 44" src="https://user-images.githubusercontent.com/13530245/122602584-147b2b00-d041-11eb-8581-cd321ab80254.png">

Current
<img width="1280" alt="Screen Shot 2021-06-18 at 19 26 30" src="https://user-images.githubusercontent.com/13530245/122602641-2fe63600-d041-11eb-9d5e-a58119a393e0.png">

**Comment by adambard1** [comment]
@ajazmi

**Comment by ajazmi** [comment]
@adambard1 Fixed
