### ISSUE TITLE
Fix Partnenaires d’Infrastructures & Énergie link on FR Secteurs d'Activités page

### ISSUE THREAD

**Issue by adambard1** [rayrshah/midisWP#19]
The link https://midisgroup.thinkdesign.com/fr/partenaires-techonologiques/#site-and-power does not go to the expected content

Source link on https://midisgroup.thinkdesign.com/fr/secteurs/
<img width="409" alt="Screen Shot 2021-06-18 at 19 37 25" src="https://user-images.githubusercontent.com/13530245/122603679-b64f4780-d042-11eb-98ea-2ce073b18a63.png">

- [x] Fix link/bookmark

WordPress
<img width="1280" alt="Screen Shot 2021-06-18 at 19 29 51" src="https://user-images.githubusercontent.com/13530245/122602973-ac791480-d041-11eb-8bb6-9ba10b08b761.png">

Current
<img width="1280" alt="Screen Shot 2021-06-18 at 19 49 29" src="https://user-images.githubusercontent.com/13530245/122604734-6ffae800-d044-11eb-8422-81e27e6e5112.png">

**Comment by adambard1** [comment]
@ajazmi

**Comment by ajazmi** [comment]
@adambard1 Fixed.
