### ISSUE TITLE
Fix Partenaires de Bureau Local link on Secteurs d'Activités page

### ISSUE THREAD

**Issue by adambard1** [rayrshah/midisWP#20]
The link on the FR page goes to https://midisgroup.thinkdesign.com/technology-partners/#local-office on the EN Technology Partners page it should go to the FR Nos Partenaires page bookmark for Bureau Local.

Source link on https://midisgroup.thinkdesign.com/fr/secteurs/
<img width="270" alt="Screen Shot 2021-06-18 at 19 57 56" src="https://user-images.githubusercontent.com/13530245/122605527-92d9cc00-d045-11eb-82bf-71116d51020b.png">

- [x] fix the link/bookmark

WordPress (goes to EN Tech Partners page) 
<img width="1280" alt="Screen Shot 2021-06-18 at 20 08 58" src="https://user-images.githubusercontent.com/13530245/122606562-1e079180-d047-11eb-9136-0b3fac0f64ce.png">

This is also an issue on the current page
The link should go to the Bureau Local bookmark:
<img width="1280" alt="Screen Shot 2021-06-18 at 20 11 55" src="https://user-images.githubusercontent.com/13530245/122606806-86ef0980-d047-11eb-9e47-97442f7752d0.png">

**Comment by adambard1** [comment]
@ajazmi

**Comment by ajazmi** [comment]
@adambard1 Link updated.
