### ISSUE TITLE
Copy edit Partenaire de distribution --> Partenaires de Distribution FR Secteurs page

### ISSUE THREAD

**Issue by adambard1** [rayrshah/midisWP#21]
Copy edit for FR Distribution link

Current
<img width="236" alt="Screen Shot 2021-06-18 at 20 21 08" src="https://user-images.githubusercontent.com/13530245/122607642-e39ef400-d048-11eb-99a9-7ae813d641c6.png">
<img width="1280" alt="Screen Shot 2021-06-18 at 20 21 04" src="https://user-images.githubusercontent.com/13530245/122607644-e4d02100-d048-11eb-94e8-35afad7d793f.png">

WordPress
<img width="227" alt="Screen Shot 2021-06-18 at 20 22 57" src="https://user-images.githubusercontent.com/13530245/122607769-11843880-d049-11eb-8cd1-d657d946da26.png">

**Comment by adambard1** [comment]
@ajazmi

**Comment by ajazmi** [comment]
@adambard1 Updated on dev site.

**Comment by adambard1** [comment]
what is the 'dev site' pls, @ajazmi ?

**Comment by ajazmi** [comment]
@adambard1 Sorry for confusion. Dev site referes new wordpress site we are working on https://midisgroup.thinkdesign.com/

**Comment by adambard1** [comment]
Ok. I cannot see the update. Saw the message about cache on issue #22 and I have cleared history/cache etc., so it must be something else stopping me from seeing the edit.
<img width="1280" alt="Screen Shot 2021-06-22 at 12 52 05" src="https://user-images.githubusercontent.com/13530245/122920226-273a7c00-d32f-11eb-9d63-a96a98cce25e.png">

**Comment by ajazmi** [comment]
@adambard1 It should be fixed now. Link text were not changed. It has been updated.
