### ISSUE TITLE
Fix Partenaires Solutions Logicielles & Services Professionnels link on Secteurs page

### ISSUE THREAD

**Issue by adambard1** [rayrshah/midisWP#23]
the link https://midisgroup.thinkdesign.com/fr/partenaires-techonologiques/#software-solutions-and-professional-services does not go to the right content

Source link on https://midisgroup.thinkdesign.com/fr/secteurs/
<img width="784" alt="Screen Shot 2021-06-18 at 20 40 29" src="https://user-images.githubusercontent.com/13530245/122609133-85bfdb80-d04b-11eb-9cd8-b47567910b3d.png">

- [ ] Fix the link/bookmark

WordPress
<img width="1280" alt="Screen Shot 2021-06-18 at 20 37 52" src="https://user-images.githubusercontent.com/13530245/122608966-2a8de900-d04b-11eb-800f-a3fdd97f2491.png">

Current
<img width="1280" alt="Screen Shot 2021-06-18 at 20 41 14" src="https://user-images.githubusercontent.com/13530245/122609209-9f612300-d04b-11eb-86e0-9f38e47f7ef9.png">

**Comment by adambard1** [comment]
@ajazmi

**Comment by ajazmi** [comment]
@adambard1 Fixed
