### ISSUE TITLE
Maintain the language choice when clicking the Midis Logo to go to the homepage

### ISSUE THREAD

**Issue by adambard1** [rayrshah/midisWP#24]
- Currently, when you click the Midis Group Logo in the Header menu to go to the home page, it goes to the EN homepage even if you are looking at FR pages.

- [ ] If you click the Midis Group Logo while browsing any page on the FR 'site', it should take you to https://midisgroup.thinkdesign.com/fr/
- [ ] If clicking it while browsing any page on the EN 'site' the logo takes you to https://midisgroup.thinkdesign.com

**Comment by adambard1** [comment]
@ajazmi

**Comment by ajazmi** [comment]
@adambard1 Fixed.
