### ISSUE TITLE
Fix Carrières page submenu items and Trouver un Travail button overlap

### ISSUE THREAD

**Issue by adambard1** [rayrshah/midisWP#26]
- This may be affected by issue #25 
- The Trouver un Travail button on the WordPress site overlaps the submenu at smaller screen sizes (below 1200w)
<img width="1228" alt="Screen Shot 2021-06-22 at 18 17 48" src="https://user-images.githubusercontent.com/13530245/122970770-4d2a4580-d35c-11eb-8337-9f60c45b32a3.png">
<img width="1099" alt="Screen Shot 2021-06-22 at 18 18 05" src="https://user-images.githubusercontent.com/13530245/122970781-4f8c9f80-d35c-11eb-8091-b13bd175530f.png">

- [ ] Fix the behavior of the Trouver un Travail button so it does not overlap the submenu. The current site solution may be appropriate, where the button remains in position till the smallest screen sizes and then the menu font size reduces ahead of the transition to portable device screen sizes.
Note: the increase in the font size in the hero section on the current site at the 991 break point is an error/issue not yet addressed
<img width="999" alt="Screen Shot 2021-06-22 at 18 20 49" src="https://user-images.githubusercontent.com/13530245/122971675-4bad4d00-d35d-11eb-991d-6e396c211f87.png">

**Comment by adambard1** [comment]
@ajazmi

**Comment by ajazmi** [comment]
@adambard1 Same solution applied as live site.
