### ISSUE TITLE
Change FR heading for carousel at bottom of page to FR (currently in EN)

### ISSUE THREAD

**Issue by adambard1** [rayrshah/midisWP#27]
Wordpress
![Screen Shot 2021-07-01 at 13 16 14](https://user-images.githubusercontent.com/13530245/124164312-85253d00-da6e-11eb-989d-1c2d16b90268.png)

Current
![Screen Shot 2021-07-01 at 13 16 33](https://user-images.githubusercontent.com/13530245/124164384-90786880-da6e-11eb-9905-baefab4baba7.png)

**Comment by seovalleygit** [comment]
@adambard1 Testmonial heading updated for FR page. @ajazmi will email with the details how to edit testimonials and heading.
