### ISSUE TITLE
Improve alignment of mobile navigation icons

### ISSUE THREAD

**Issue by adambard1** [rayrshah/midisWP#28]
![Screen Shot 2021-07-01 at 13 19 15](https://user-images.githubusercontent.com/13530245/124164743-0a105680-da6f-11eb-94da-fed182d1be05.png)

**Comment by seovalleygit** [comment]
@adambard1 @ajazmi Improved alignment.
![image](https://user-images.githubusercontent.com/86654942/124259520-3948c580-db4c-11eb-99d4-e6f57f1013c8.png)

**Comment by adambard1** [comment]
Great!
