### ISSUE TITLE
Prevent ellipsis in affiliate tiles when all information appears in the tile

### ISSUE THREAD

**Issue by adambard1** [rayrshah/midisWP#29]
There are only 6 offices for this affiliate yet an ellipsis appears in the tile on WP, suggesting there are further offices.

WordPress
![Screen Shot 2021-07-01 at 13 36 37](https://user-images.githubusercontent.com/13530245/124166870-61afc180-da71-11eb-9dc2-a0464d44eb30.png)

Current
![Screen Shot 2021-07-01 at 13 39 56](https://user-images.githubusercontent.com/13530245/124167256-d71b9200-da71-11eb-8674-d72aa151037c.png)

- [ ] Prevent ellipsis when all information is visible

**Comment by adambard1** [comment]
@ajazmi

**Comment by adambard1** [comment]
@krishna711

**Comment by seovalleygit** [comment]
@adambard1 Issue Fixed. Updated to show ellipsis only when more offices present.
