### ISSUE TITLE
No backslash should appear where quotation marks are in Affiliate name

### ISSUE THREAD

**Issue by adambard1** [rayrshah/midisWP#3]
Affiliates directory tiles for Southcomp Distribution Maroc ”SCDM” SARL and Southcomp Distribution Tunisie ”SDT” SARL are showing the Affiliate name with a backslash ahead of the quotation mark.
Current
![Screen Shot 2021-06-11 at 10 28 53](https://user-images.githubusercontent.com/13530245/121702393-d65d9480-ca9f-11eb-9792-0b04eb08cada.png)
![Screen Shot 2021-06-11 at 10 28 48](https://user-images.githubusercontent.com/13530245/121702421-dbbadf00-ca9f-11eb-8313-5259da94394d.png)

WordPress
![Screen Shot 2021-06-11 at 10 26 20](https://user-images.githubusercontent.com/13530245/121702009-7d8dfc00-ca9f-11eb-995a-4845b540efd1.png)

- [ ] remove Backslash and prevent further instances

To check on the cause, [possible clues may be here](https://bbpress.org/forums/topic/apostrophe-and-or-quotation-marks-cause-backslash-to-appear/)...

figma comments [128](https://www.figma.com/file/oH0sJGfswfMBtm4aenKOl4?node-id=1624:8#86935034) and 129 show this issue

**Comment by adambard1** [comment]
@ajazmi are you notified without me @mentioning you in the issue thread?

**Comment by ajazmi** [comment]
@adambard1  It has been fixed. Kindly check it.

**Comment by adambard1** [comment]
Thenk you. EN is fixed, FR directory is not yet fixed @ajazmi 

<img width="920" alt="Screen Shot 2021-06-16 at 08 24 59" src="https://user-images.githubusercontent.com/13530245/122218359-5eff7a80-ce7c-11eb-895b-abbf281c2e99.png">

**Comment by ajazmi** [comment]
@ adambard1 Fixed for FR Directory.

**Comment by adambard1** [comment]
This is done
