### ISSUE TITLE
Add language selection header to the Affiliates x Technology Partners pages

### ISSUE THREAD

**Issue by adambard1** [rayrshah/midisWP#34]
WordPress page is missing the heder with the language selection
WordPress
![Screen Shot 2021-07-02 at 13 57 04](https://user-images.githubusercontent.com/13530245/124312615-9721e100-db3d-11eb-8f18-79d85532c2d8.png)

Current
![Screen Shot 2021-07-02 at 13 58 18](https://user-images.githubusercontent.com/13530245/124312661-af91fb80-db3d-11eb-97dd-c969b0d7a53b.png)

**Comment by adambard1** [comment]
@seovalleygit @ajazmi

**Comment by seovalleygit** [comment]
@adambard1 Language selection link included.
