### ISSUE TITLE
To test on Back end

### ISSUE THREAD

**Issue by adambard1** [rayrshah/midisWP#36]
Creation and editing of content, FR and EN

- [x] News article
- title (H1)
- subheading (H2)
- body copy
- image, inc caption, and alt text
- draft and publish setting

- [x] Affiliates
- add new and editing/delete existing
- logo
- channel
- SEO descriptive text
- URL
- contact details
- partner logos
- second office details
- is linking of affiliate to partners automatic through adding their logos?

- [x] Technology partners
- new partner
- logo
- link to affiliate(s)
- channel

- [ ] Pages (general)
- Headings
- Sections
- is the equivalent FR layout/section created automatically?

- [x] Geolocation
- CMS should provide instructions for reciprocal creation
- check Filter is not automatically applied
- is an automated email sent?

- [x] Popup
- Global or Frontpage selection
- Are there instructions?

- [ ] Carousel function
- add image
- add quote

- [ ] Image editing

**Comment by adambard1** [comment]
@rayrshah @kiran-td

**Comment by kiran-td** [comment]
Hi Adam and Ray Here is my comments on each point. Some of issues already mentioned by adam in previous tickets.  Carousel function and image editing is remaining to test which i will do it later tonight. Also i have added some frontend feedback as well.

Frontend
- Back to top button is missing in affiliate detail page
- How you define the region availability in frontend? as currently my post appear in africa. As i have selected region africa and middle east both? If it's specific to country then i have select my home coutry usa. Either we have to keep selection only to one region.
- There is no <h1> found in affiliate detail page

Backend

News article
- By default no subheading. If you enter any from description it'll available
- After adding any post when you enter data to other lanague, when you copy the content, country box does not have autofill like category have.


Affialiates

- In affialiate page some things is confusion. it would be good to have label for example Sr.Executive (enter name here) something like this. I've insert Yes initially as i don't understand the usage of field.
- If we are not using Countries and regions
- Partners seems not working proper on change where channel is selected. If we are displaying all the partners then in frontend data would be goes wrong. For example i have selected channel Software solutions and professional services. And add partner blue coat which is from system integration. So when you see https://midisgroup.thinkdesign.com/partners/afffiliates-representing-blue-coat/
associated affialite with partner it's wrong. as i have business in channel software solution not in system integration. Solution is simple display technology partner when any channel selected.

Technology partner
- Seems ok 
- Frontend technology partner detail pages doesn't have <h1>

Geolocation

CMS should provide instructions for reciprocal creation
>> I think it's as per plugin used however no custom instructions available
check Filter is not automatically applied
>> When you copy content from original post side attributes missing sometime 

is an automated email sent?
>> I dought that as of now any email are going to send

Popup

Global or Frontpage selection

Are there instructions?
>> No i am not able to find any popup.

Also there is one suggestion. If client have more visits or customer base from EU they should display cookie policy popup when visit first time as per EU low.

**Comment by adambard1** [comment]
> Popup
> 
> Global or Frontpage selection
> 
> Are there instructions?
> 
> > > No i am not able to find any popup.

There are popup settings: Custom Fields > Popup settings
Though they are too complex for me, I would hide most of them
The popup creation is called 'Dialogs' and is a field to upload media

**Comment by seovalleygit** [comment]
@adam-td @ajazmi 

These options taken from current site behavour. Explaining each setting what it does.

![image](https://user-images.githubusercontent.com/86654942/127128452-ca6a7403-09ce-405e-9158-76c30fd9a315.png)

Always Display: On/Off If ON popup will be on always. If OFF popup will display only once every 72 hours. If Display on Entire Site setting is OFF and there is no page selected then this setting has no effect. This has been borrowed from current site.

Display on Entire Site: Keep it on if you wish to shop popup on sitewide.
Display On Page: Select specific pages on which you want to show pip

Dialogs can be rename to popup if needed. It was named as Dialogs in current site so kept it same.
