### ISSUE TITLE
Enable multi-line address entry for affiliates in the back and and visibility if filled in on the front end

### ISSUE THREAD

**Issue by adambard1** [rayrshah/midisWP#37]
To enable multiline address entry in the future, two more fields address_2 and address_3 have been added to the Affiliate Details section through the Affiliate Details Field Group.

- [ ] Enable address_2 and Address_3 to appear on the front end if filled in. These would align under the first address field as sown below.
- [ ] If user adds address fields these too should appear on the front end in the position defined by the user – e.g. if an address-4 field is added
- [ ] This is to enable multi-line address display as in the [Figma](https://www.figma.com/file/xfeXe5BWo5CbJ29BYbQKn1/Midis-UI-changes?node-id=693%3A746)
![Screen Shot 2021-07-06 at 10 40 23](https://user-images.githubusercontent.com/13530245/124619383-9becda80-de46-11eb-9aac-2fbd482cbffe.png)

**Comment by adambard1** [comment]
@ajazmi @seovalleygit

**Comment by seovalleygit** [comment]
@adambard1 @ajazmi  Added Address 2, 3 and 4 field in backend and frontend. 
![image](https://user-images.githubusercontent.com/86654942/124800856-c1c3cd80-df73-11eb-9f10-16ce77baa667.png)
