### ISSUE TITLE
City and Location fields in Affiliate details do not appear on the front end?

### ISSUE THREAD

**Issue by adambard1** [rayrshah/midisWP#38]
Currently, only address field 1 on the affiliate details appears as the address on the front end.

- What are the City and Location fields for?
e.g.
![Screen Shot 2021-07-06 at 10 48 31](https://user-images.githubusercontent.com/13530245/124620809-c1c6af00-de47-11eb-97d0-1da44168edb3.png)

**Comment by adambard1** [comment]
This is related to issue #37

**Comment by adambard1** [comment]
@ajazmi @seovalleygit

**Comment by adambard1** [comment]
also related to #39

**Comment by seovalleygit** [comment]
@adambard1 City was already included in full address in most of the affliates that is the reason it is not included in front-end. In the old cms, it was separate field as well. That is the reason I took it same structure in wordpress. We can add city in address if it not already present in address. Please advice. Location field can be removed as well if not required. 

![image](https://user-images.githubusercontent.com/86654942/124721597-e0e83e00-df26-11eb-84b2-24610046d139.png)
