### ISSUE TITLE
Affiliate City should appear on the front end in the contact details

### ISSUE THREAD

**Issue by adambard1** [rayrshah/midisWP#39]
Though an Affiliate City appears in the Affiliate Detail 'City' field, it does not appear on the front end. e.g. for [BMS](https://midisgroup.thinkdesign.com/wp/wp-admin/post.php?post=1849&action=edit&lang=en)
![Screen Shot 2021-07-06 at 10 55 22](https://user-images.githubusercontent.com/13530245/124621956-ae681380-de48-11eb-8171-9c2a4af6e3a1.png)

![Screen Shot 2021-07-06 at 10 52 31](https://user-images.githubusercontent.com/13530245/124621581-63e69700-de48-11eb-9ebd-c747c41fa4bc.png)

- as in #38 the Address field is the only field being displayed on the font end

- [x] Enable City to appear on the front end, if it is not duplicating existing information.

**Comment by seovalleygit** [comment]
@adambard1 @ajazmi City field added in frontend if not present in address. It will be added in new line. Address 2 and Address 3 also added. Address 2 and Address 3 will be added in new line if added.

**Comment by ajazmi** [comment]
@seovalleygit - Yes, please add 2 more options further in the form of Address Line 2 & Address Line 3. For now, only this functionality is needed, the data entry needs to remain the same as is.

**Comment by seovalleygit** [comment]
@adambard1 @ajazmi Address 2, 3, 4 added in frontend. It will display as new line if entered.

**Comment by adam-td** [comment]
We have amended this, though I am leaving it open till I understand the fields we want visible on the back end.
