### ISSUE TITLE
Show only 2 lines of content for Countries on Affiliate directory tiles

### ISSUE THREAD

**Issue by adambard1** [rayrshah/midisWP#4]
- [ ] Only show max 2 lines of countries content on affiliate tiles in affiliate directory. Add ellipsis to indicate further countries are served.

e.g. as for (current site) affiliate tiles DFST Cyprus, or Miver Europe. 
Current
![Screen Shot 2021-06-11 at 10 20 16](https://user-images.githubusercontent.com/13530245/121701207-a95cb200-ca9e-11eb-8f9e-557105445479.png)
WordPress
![Screen Shot 2021-06-11 at 10 19 07](https://user-images.githubusercontent.com/13530245/121701035-803c2180-ca9e-11eb-9a2d-9f90515f0178.png)

Southcomp Polaris also adds ellipsis even though countries would fit on 2 lines.
Current
![Screen Shot 2021-06-11 at 10 17 40](https://user-images.githubusercontent.com/13530245/121700821-44a15780-ca9e-11eb-8893-c31f1b6e9e00.png)
WordPress
![Screen Shot 2021-06-11 at 10 23 38](https://user-images.githubusercontent.com/13530245/121701638-196b3800-ca9f-11eb-8f49-ef604773aed5.png)

Issue is noted in Figma comments 127, 130 and 131

**Comment by adambard1** [comment]
@ajazmi

**Comment by ajazmi** [comment]
@adambard1 It is updated to keep countries content in two line only.

**Comment by adambard1** [comment]
Done, thanks
