### ISSUE TITLE
Duplicate City data appears in some Affiliate Detail Fields

### ISSUE THREAD

**Issue by adambard1** [rayrshah/midisWP#40]
Several affiliates show the City in the Location field as well as the City field and the Address field
e.g. (for [MCIMA-SARL AU](https://midisgroup.thinkdesign.com/wp/wp-admin/post.php?post=2193&action=edit&lang=en))
![Screen Shot 2021-07-06 at 10 48 31](https://user-images.githubusercontent.com/13530245/124623000-947b0080-de49-11eb-8072-6a81caf0ca02.png)

- Why is there duplicate information in these fields and can we fix it so the City appears only in the City field and the Country in its own field "Country"?

**Comment by adambard1** [comment]
connected to issues #37 #38 #39

**Comment by adambard1** [comment]
@ajazmi @seovalleygit

**Comment by seovalleygit** [comment]
@adambard1 @ajazmi Can we use home country field instead of using new country field. Home County field also belong to same address. 
![image](https://user-images.githubusercontent.com/86654942/124728397-30ca0380-df2d-11eb-8da6-2e367d561324.png)

**Comment by adambard1** [comment]
@ajazmi has pinged @seovalleygit to amend the address entry so that there is a text field that respects line breaks.

**Comment by adambard1** [comment]
i.e. the address filed will look like this on the front end
![Screen Shot 2021-07-13 at 08 12 10](https://user-images.githubusercontent.com/13530245/125449463-fd02374b-7b31-4a5c-9f0f-553ba6aa0d42.png)

**Comment by seovalleygit** [comment]
@adambard1 @ajazmi Address field change to text area with multiline support. Front end updated to show multiline address.
