### ISSUE TITLE
Provide instructions for editing Affiliate x Tech Partners links

### ISSUE THREAD

**Issue by adambard1** [rayrshah/midisWP#41]
@ajazmi where do you edit the hyperlink for the technology partners that creates the relevant Affiliate x Tech Partners page, pls?

e.g. I have edited and published the change to the name and the slug for the previously mislabeled Kidde Technologies (wrongly called Kiddie Technologies) [in the Yoast module of the Edit Technology Partner page](https://midisgroup.thinkdesign.com/wp/wp-admin/post.php?post=1357&action=edit&lang=en)
so the partner and the slug are correct:
![Screen Shot 2021-07-06 at 13 34 57](https://user-images.githubusercontent.com/13530245/124643329-f8f48a80-de5e-11eb-953e-110749b40eed.png)

- But the link under the partner logo remains unchanged

![Screen Shot 2021-07-06 at 13 48 54](https://user-images.githubusercontent.com/13530245/124645110-07dc3c80-de61-11eb-885f-93ea5ae4cf0a.png)

- And the created Affiliate x Tech partner page is not corrected

![Screen Shot 2021-07-06 at 13 41 22](https://user-images.githubusercontent.com/13530245/124644085-dc0c8700-de5f-11eb-864a-4e7e3981ce73.png)

- Search returns results for both the correct and incorrect partner name

![Screen Shot 2021-07-06 at 13 46 19](https://user-images.githubusercontent.com/13530245/124644694-8d132180-de60-11eb-9e76-099a7a2083be.png)
![Screen Shot 2021-07-06 at 13 47 10](https://user-images.githubusercontent.com/13530245/124644824-ab791d00-de60-11eb-9469-ecd386384035.png)

- **Is there another place to edit the partner name and the hyperlink link, not in the Yoast module?**

**Comment by seovalleygit** [comment]
It has been corrected. I see corrected link now. May be temp cache issue.

Slug/Permalink can be change from yoast module as well as option below the title input.

![image](https://user-images.githubusercontent.com/86654942/124711658-f99f2680-df1b-11eb-9bfa-f68c3f69fb44.png)

**Comment by seovalleygit** [comment]
@adambard1
