### ISSUE TITLE
Enable publication date on the front end for HR News Stories.

### ISSUE THREAD

**Issue by adam-td** [rayrshah/midisWP#44]
As per the existing site. We can address this after launch unless it is a trivial fix, then go ahead.

- HR News has no date of publication e.g.
![Screen Shot 2021-07-22 at 10 21 42](https://user-images.githubusercontent.com/87426372/126655383-e50be62b-3a2c-45c7-accf-58a63c60fe62.png)

- News Articles have a date of publication. e.g. as below
- Am confirming with client how this will function (e.g. automatic on publication, auto + editable before and after pub, or manual entry)
![Screen Shot 2021-07-22 at 10 22 12](https://user-images.githubusercontent.com/87426372/126656537-318ed2f9-2f9c-4fe6-9bd7-f4ec0588df86.png)

**Comment by seovalleygit** [comment]
@adam-td @ajazmi Publication date added. It is chanable at the time of publishing, before and after publishing. 

![image](https://user-images.githubusercontent.com/86654942/126758834-83db3b8d-8e23-48f7-b90b-10810ecc7a08.png)

**Comment by adam-td** [comment]
Thank you. Having heard from the content creator, Jon, confirming that it
automatically creates the publication date when first saved as a draft? His
message below on how it is expected to work:

"Re the dates - the mechanism should be the same as currently on news
stories. i.e. it is automatically set when you save a first save a story,
and then it can be changed manually if the need arises. The need does arise
sometimes.

When I upload French stories at the moment, I back date them to when the
English version was dated.

Sometimes stories stay unpublished for ages, waiting for affiliate
approval, and then I redate them to the present when affiliate permission
arrives and they go live."

**Comment by seovalleygit** [comment]
@adam-td @ajazmi Yes, it works same as current site. It uses date when first time content is saved. Later on if required date can be changed.
