### ISSUE TITLE
In News and HR News Articles bottom margin under the video or image caption to be 2.25 rem

### ISSUE THREAD

**Issue by adam-td** [rayrshah/midisWP#45]
Currently, we have a 3 rem bottom margin under the caption following images or video on HR news and News articles
e.g.

- this HR News article 3 rem gap
![Screen Shot 2021-07-22 at 10 47 56](https://user-images.githubusercontent.com/87426372/126659390-6186f8bc-eedc-4d43-906c-e2b5ee3c095f.png)

- The Current site has a 2.25 rem gap
![Screen Shot 2021-07-22 at 10 50 30](https://user-images.githubusercontent.com/87426372/126659880-f9b0a599-8167-4b6d-8466-8e2ca4108eab.png)

- [ ] match the current site and establish a 2.25 rem margin between images or video and their following content in all News and HR News articles

**Comment by adam-td** [comment]
The current site's News articles have a 3 rem margin, so this is where I expect you have established the margin. It is a persistent bug on the existing site and should be as described above.

**Comment by seovalleygit** [comment]
@adam-td @ajazmi Updated as current site.
