### ISSUE TITLE
Fix Position of Affiliate x Tech partners link after creating a new Tech partner

### ISSUE THREAD

**Issue by adam-td** [rayrshah/midisWP#46]
The link does not align with the other links created.
![Screen Shot 2021-07-22 at 11 07 55](https://user-images.githubusercontent.com/87426372/126662705-0595ef06-ee81-424c-a924-53859b276b46.png)

**Comment by adam-td** [comment]
- Existing
![Screen Shot 2021-07-22 at 11 10 30](https://user-images.githubusercontent.com/87426372/126672695-a3d58ab2-2fd0-4591-a83c-59b91c247985.png)

-New
![Screen Shot 2021-07-22 at 11 10 47](https://user-images.githubusercontent.com/87426372/126672693-2c0f0280-7983-444c-9def-750a2a9cb0f9.png)

**Comment by seovalleygit** [comment]
@adam-td @ajazmi Fixed positining.
