### ISSUE TITLE
Align new Tech partner logo image, to align with existing Partners

### ISSUE THREAD

**Issue by adam-td** [rayrshah/midisWP#47]
When creating a new Tech partner the uploaded logo should be in line and sized as per other images and link
- existing
![Screen Shot 2021-07-22 at 11 10 30](https://user-images.githubusercontent.com/87426372/126663243-96aa891f-0a69-40ff-b5f7-0f50771e8227.png)

- added

![Screen Shot 2021-07-22 at 11 10 47](https://user-images.githubusercontent.com/87426372/126663165-665ad5b1-d504-4adb-a00f-d1fb0aaf7ac7.png)

**Comment by adam-td** [comment]
probably same issue as #46

**Comment by seovalleygit** [comment]
@adam-td @ajazmi Fixed with issue #46
