### ISSUE TITLE
Duplicate FR or EN new Affiliate and Tech Partner content on back end without publishing

### ISSUE THREAD

**Issue by adam-td** [rayrshah/midisWP#49]
When the client creates a new affiliate or Tech partner, this should be duplicated as a draft in the other language, leaving the client to publish it once confirming the translation and settings

**Comment by seovalleygit** [comment]
@adam-td @ajazmi This option is already provided by WPML plugin once we save post first time. I think we should leave it as it is as automating this process may interfare with default functionality of plugin. 

![image](https://user-images.githubusercontent.com/86654942/126774510-bd250ee2-fe6e-4c11-9d6c-433950bc0719.png)

**Comment by adam-td** [comment]
I'd like to confirm, does this checkbox have to be selected manually by the
content creator for every content entry they want duplicating – can we
enable it to be checked by default for Affiliate and Tech Partner content?

Also, will it operate after the fact – if content has been created and the
box is checked subsequently, will a duplicate page be created?

**Comment by seovalleygit** [comment]
@adam-td @ajazmi I have enabled checkbox by default.  There will be Duplicate button beneath check box. Duplicate post will be created only when this button will be clicked. 

Checkbox and button will disappear once duplicate post created. So, there is no chance of duplicate post subsequently. 

![image](https://user-images.githubusercontent.com/86654942/127137321-18ef484d-ff5c-45a0-ba0d-b9137eb87af7.png)

**Comment by adam-td** [comment]
We tested this today. A fix is still needed to prevent publishing duplicated content. @seovalleygit is working on it.

**Comment by seovalleygit** [comment]
@adam-td @ajazmi Fixed. Duplicate posts will be saved as with draft status.

**Comment by adam-td** [comment]
Great thanks, Bala.
