### ISSUE TITLE
Rename backend "ourhistory" value to "workingwithus" ?

### ISSUE THREAD

**Issue by adam-td** [rayrshah/midisWP#50]
I have renamed the label in the field, but I did not know if there was a consequence to changing the name of the value, so left it. It should be renamed for consistency so we all know what we are talking about.

<img width="931" alt="Screen Shot 2021-07-22 at 11 50 50" src="https://user-images.githubusercontent.com/87426372/126669542-5156b09f-12ee-4294-8fd2-256c4c37d66c.png">

**Comment by seovalleygit** [comment]
@adam-td @ajazmi Updated value on backend and frontend at relavant places. 

![image](https://user-images.githubusercontent.com/86654942/127123948-4a8525b1-7a1c-4d3d-be56-bd3ccddf81ea.png)
