### ISSUE TITLE
Confirm how client can share previews

### ISSUE THREAD

**Issue by adam-td** [rayrshah/midisWP#53]
We expect this will be through providing guest login details for previews, or that previews will be shared to existing authenticated users, but if preview links can be shared without this extra measure that would be good.

**Comment by seovalleygit** [comment]
@adam-td @ajazmi It is not possible enable preview button under publish box. This option will be available only when post is in draft mode. To check this function first unpublish post then enable preview option. Copy link and share it. 

Test affliate preview link: https://midisgroup.thinkdesign.com/?p=7831&post_type=affiliate&preview=1&_ppp=bd2cf0ac3f

![image](https://user-images.githubusercontent.com/86654942/126773617-5fba209d-5685-421a-bfe4-a5b87378eef6.png)

**Comment by adam-td** [comment]
How long are the links valid – testing the link above today it says the link is expired.

**Comment by seovalleygit** [comment]
@adam-td @ajazmi Link is valid for 48 hrs but time can be increase if required.

**Comment by adam-td** [comment]
OK, got it.
