### ISSUE TITLE
Remove or hide the Multilingual Content Setup field group

### ISSUE THREAD

**Issue by adam-td** [rayrshah/midisWP#54]
- [ ] Hide this group if the radio button position should not be changed
<img width="948" alt="Screen Shot 2021-07-22 at 11 44 32" src="https://user-images.githubusercontent.com/87426372/126672500-15df20f4-8546-486f-8d3e-57ddb516b0a1.png">

**Comment by seovalleygit** [comment]
@adam-td @ajazmi Removed
