### ISSUE TITLE
Fix top alignment of Affiliate Icon and Affiliate Title on Affiliate detail page

### ISSUE THREAD

**Issue by adam-td** [rayrshah/midisWP#57]
The Affiliate title font, the top of the company logo and the 'back to directory...' button should all be top aligned. The font is a bit off.

<img width="1038" alt="Screen Shot 2021-07-29 at 10 53 07" src="https://user-images.githubusercontent.com/87426372/127521824-43163458-210a-45fd-a565-80b0a5db261b.png">

**Comment by seovalleygit** [comment]
@adam-td @ajazmi Updated. aligned with the image top and back button.
