### ISSUE TITLE
Fix distortion of new tech partner logo images added to the Affiliate detail page, or provide documentation on its max size

### ISSUE THREAD

**Issue by adam-td** [rayrshah/midisWP#58]
Related to #59 – the tech partner featured image uploaded in #59 is very distorted [on the corresponding Affiliate detail page](https://test.midisgroup.com/affiliates/adams-bay-ridge-coffee-shop/).

- [ ] The size of the featured image in #59 must account for the scaling that occurs on the Affiliate Detail page
<img width="599" alt="Screen Shot 2021-11-02 at 12 30 32" src="https://user-images.githubusercontent.com/87426372/139906849-8aea7a1f-6945-444a-acce-71b32f29dfd2.png">

**Comment by adam-td** [comment]
max size of logo can be provided as in #59

**Comment by krishna711** [comment]
@adam-td @rayrshah @ajazmi partner logo size is automatically scaling at 94x98px in the current site and https://test.midisgroup.com site from original image. It will look fine when uploaded in required size 280x199px. We can add additional image box along with feature image box if required for this specific location.

**Comment by adam-td** [comment]
providing documentation and written on the cms

**Comment by krishna711** [comment]
@adam-td @rayrshah Document Updated #48
