### ISSUE TITLE
Provide Information on size of Featured Image for Tech partner

### ISSUE THREAD

**Issue by adam-td** [rayrshah/midisWP#59]
The image uploaded for [this test tech partner](https://test.midisgroup.com/wp/wp-admin/post.php?post=9288&action=edit&lang=en) (the 3t logo) appears distorted.

<img width="1154" alt="Screen Shot 2021-11-02 at 12 27 11" src="https://user-images.githubusercontent.com/87426372/139905879-d224fe32-ca6a-4828-bd55-00e2a14b8a9b.png">

- [ ] Publish the maximum dimensions, or appropriate ratio for a featured image on the CMS page, and/or, provide a warning for the user to scale the image.

**Comment by adam-td** [comment]
Also add this information to the Documentation #48.

**Comment by krishna711** [comment]
Added size requirement details in the box. Also, I will add this in document. 
![image](https://user-images.githubusercontent.com/2379768/140018225-c891b813-97b8-4eda-be61-06230c04429b.png)
