### ISSUE TITLE
Publish channel (commercialisation) of all FR affiliates in their affiliate tile

### ISSUE THREAD

**Issue by adambard1** [rayrshah/midisWP#6]
The WordPress site is showing affiliates that are not published to the Directory on the current site.

- [x] Match the publicly visible directory listings for both the EN and FR Directories (they are different)
- [x] Enable draft Affiliate content in the backend to be hidden from the published directory
- [ ] Enable independent draft selection for EN and FR Affiliate Directories

Below, for the current site, IDM is in the backend FR directory but not in the EN Directory though the WordPress site publishes it in both the EN and FR Directory.

e.g. Discrepancies in listing Affiliates in the Directory (showing a selection of EN Middle-East Affiliates)
Current
![Screen Shot 2021-06-11 at 10 50 57](https://user-images.githubusercontent.com/13530245/121705773-fb9fd200-caa2-11eb-8b50-541f0cbcfd12.png)
WordPress
![Screen Shot 2021-06-11 at 10 51 03](https://user-images.githubusercontent.com/13530245/121705791-00fd1c80-caa3-11eb-930e-ce3fc44c46f8.png)
note, possible bug: in Forestry, IDM only appears in the FR backend Directory, but not on the front end, though it is not a draft.

**Comment by adambard1** [comment]
We can split this ticket into different issues if that is helpful to resolving issues for the Affiliate Directory listings.

**Comment by adambard1** [comment]
sharing conversation with the developer of the current site...

rayshah  12:11 PM
If the affiliate is in one language, it should be in both or in neither AFAIK

Régis  12:12 PM
Hi @Adam Bard affiliates share many data across languages so they have to be entered in the EN directory with full data. Then their FR counterpart in the FR directory can supplement some of the data with its own. But they cannot be in en FR alone to be taken into account.
12:12
I think we cleared that with Ray when implementing a long time ago, which his last comment confirms. (edited) 

Adam Bard  12:13 PM
If they only get deleted in the EN directory does that leave data in the FR directory?

Régis  12:13 PM
For me, an Affiliate being in only one language is a novelty. It’s not built for that.
12:13

Adam Bard
 If they only get deleted in the EN directory does that leave data in the FR directory?

Régis
12:14
It leaves the data but it won’t show up in list pages in neither languages
12:14
Our point of source is the English directory, and then we find their french counterparts when visiting the “french” site.

Adam Bard  12:15 PM
OK, so is it possible one of the content team just entered IDM in the FR directory back end, so it wouldn’t have published it (though it exists as the affiliate detail page)?

Régis  12:15 PM
Yes

**Comment by adambard1** [comment]
@ajazmi

**Comment by ajazmi** [comment]
@adambard1 Compared EN live and new site and added/removed missing affliates with updated data. Working on FR directory.

**Comment by ajazmi** [comment]
@adambard1 FR directory compared and updated as per live site.

**Comment by adambard1** [comment]
FR Directories showing discrepancies around the publishing of the Channel. The current site only publishes the Distribution channel (commercialisation) for each FR affiliate. The WordPress site publishes all channels, though some appear to have no information to publish

AB to check with Client about publishing FR commercialisation

WordPress example
![Screen Shot 2021-07-01 at 15 29 25](https://user-images.githubusercontent.com/13530245/124180021-99266a00-da81-11eb-97b4-d33888d96561.png)

Current (same affiliates)
![Screen Shot 2021-07-01 at 15 30 05](https://user-images.githubusercontent.com/13530245/124180080-af342a80-da81-11eb-8950-6d6edc1b261d.png)

**Comment by seovalleygit** [comment]
@adambard1 We can remove commercialisation where is applicable on FR side. Current site is showing blank commercialisation: In wordpress we are hiding commercialisation: heading if blank. Please advise if this behaviour need to change as per current site where commercialisation showing even if it is blank.

**Comment by adam-td** [comment]
Client confirms that all channels entered should show in both EN and FR
