### ISSUE TITLE
Custom code for geo targeted content

### ISSUE THREAD

**Issue by rayrshah** [rayrshah/midisWP#60]
Hi,

Is this plugin a good option for geo targeting content?

https://geotargetingwp.com/geotargeting-pro

the alternatives involve getting a code back from a CDN like cloudflare and altering site logic accordingly

**Comment by rayrshah** [comment]
@krishna711 

I think this is easier than [Configuring-Cloudflare-IP-Geolocation ](https://support.cloudflare.com/hc/en-us/articles/200168236-Configuring-Cloudflare-IP-Geolocation)

There Is  a free 2-week trial period. Let's try it.

Guys - I think this Is  the last issue we need to fix before going live.

**Comment by rayrshah** [comment]
[countries_sensitivities.xlsx](https://github.com/rayrshah/midisWP/files/6913687/countries_sensitivities.xlsx)

These are the rules. 

* Any content associated with Qatar should not be visible in UAE, Egypt, Bahrain and Saudi Arabia
* Any content associated with UAE, Egypt, Bahrain or Saudi Arabia should not be visible in Qatar

**Comment by seovalleygit** [comment]
@rayrshah @adam-td @ajazmi Hello Ray, the Geotargetting feature can be code with or without a plugin. Can you advise what is the country-specific content area is on the website? 

I assume you are referring affiliate directory in this case.
Qatar affiliates should not be visible to UAE, Egypt, Bahrain, and Saudi Arabia country visitors.
UAE, Egypt, Bahrain, and Saudi Arabia affiliates should not be visible to Qatar country visitors.

Is this what we need to achieve?

Thank You.

**Comment by rayrshah** [comment]
Yes @seovalleygit 

At least in part. We also need to exclude any content that is tagged with that country. For example if a new istyle store opens in Dubai, the story about the store opening should not be visible in Qatar.

**Comment by rayrshah** [comment]
In the current CMS, we have country as a field.

It can be populated with one or more countries.

Is a similar feature enabled in WordPress as yet?

**Comment by rayrshah** [comment]
@seovalleygit these rules apply to all content

**Comment by seovalleygit** [comment]
@rayrshah @adam-td @ajazmi  News, HR News, Affiliates have country fields. We can filter content based on this country field.

**Comment by rayrshah** [comment]
@seovalleygit how Is  this coming, can we have an update pls?
@adam-td

**Comment by seovalleygit** [comment]
@adam-td @rayrshah @ajazmi Still working on it. It will be completed by tomorrow.

**Comment by seovalleygit** [comment]
@rayrshah Can you give me the name of the VPN software you are using to change geolocation? I tried a few software but none of them properly working.

**Comment by rayrshah** [comment]
Private Internet Access @seovalleygit

**Comment by seovalleygit** [comment]
@rayrshah @adam-td @ajazmi 

Geo Feature Coded. Please check screenshot below to know how it works. Setting page has feature to set mode to one direction or bi-directional. So we don't need to add new rule for opposite direction.

![image](https://user-images.githubusercontent.com/86654942/129346929-f189fe26-76cc-41dc-88d3-39800d7b45cd.png)

Rules apply to News page, Search page, Affliate Listing and Filters.

**Comment by rayrshah** [comment]
@seovalleygit @ajazmi 

Bala. This looks great. @adam-td has new copy for the instructions:

### Target region
Website visitors in:
[Qatar]
### Source region
Will not see content about or from:
[Saudi, Bahrain… etc.]
#### Direction
- [ ] Unidirectional – Target region does not see content about or from Source region
- [ ] Bidirectional – Target and Source regions do not see content about or from each other

@seovalleygit can you implement this. As soon as I have new hosting info, I will pass it along to you.

**Comment by seovalleygit** [comment]
@rayrshah @adam-td @ajazmi Sure, I will update as per the suggestion by tomorrow.

**Comment by seovalleygit** [comment]
@rayrshah @adam-td @ajazmi Settings UI updated.

**Comment by adam-td** [comment]
Hi @seovalleygit thanks for this though there is a bit of a misinterpretation of the copy. The copy in the square brackets was just meant to symbolize the chosen countries that were showing. Please remove the brackets and countries mentioned from the UI.
<img width="784" alt="Screen Shot 2021-08-14 at 12 44 37" src="https://user-images.githubusercontent.com/87426372/129453486-1963900e-bcef-458d-94cb-eedb49f09f22.png">

- [ ] Also, can the Source region selection go above the Direction selection please, so the order of work. top to bottom is selecting the Target Region, then selecting the Source Region then the Direction of the filter

**Comment by rayrshah** [comment]
Hey @seovalleygit 
Can  you make this work? It currently appears not to. 

I'm connected through Egypt,  yet I can see Qatari entries in the  affiliate directory. 

Please let @rayrshah @adam-td  know when to test again.

![image](https://user-images.githubusercontent.com/2479135/129482523-660e29c0-310b-4b00-ac1e-1768f85342ce.png)

**Comment by seovalleygit** [comment]
@rayrshah @adam-td @ajazmi Code updated to support it. Please test now. Thanks

**Comment by rayrshah** [comment]
OK, it appears to work from Egypt

- [ ] can you also filter on search?

**Comment by seovalleygit** [comment]
@rayrshah I fixed the code to exclude country on the search page. Also, the country was not assigned to this post. Posts filter works on this field so it should be filled if applicable. 

![image](https://user-images.githubusercontent.com/86654942/129656343-c0dca49a-fc34-40a3-9e6b-12f7cf4d358f.png)

**Comment by rayrshah** [comment]
@seovalleygit 

https://midisgroup.thinkdesign.com/abc-signs-agreement-with-bank-nizwa-implementing-latest-dell-technologies-solutions/

This 404 page should show up when the URL for a restricted page is  used:

https://www.midisgroup.com/abc-signs-agreement-with-bank-nizwa-implementing-latest-dell-technologies-solutions/
![image](https://user-images.githubusercontent.com/2479135/130340478-bf90cedf-859f-4af9-bcf7-a5c1f61c7eac.png)

**Comment by seovalleygit** [comment]
@rayrshah @adam-td @ajazmi I will code it today and update you.
