### ISSUE TITLE
Speed up test.midisgroup.com

### ISSUE THREAD

**Issue by rayrshah** [rayrshah/midisWP#64]
The Lighthouse performance score has lots of room for improvement, can we address this?

![image](https://user-images.githubusercontent.com/2479135/131862697-4d1e51a5-2695-4331-b11b-803c315a17e4.png)

**Comment by seovalleygit** [comment]
@rayrshah @adambard1 @ajazmi Looking into these improvements.

**Comment by rayrshah** [comment]
https://updown.io/58rh

let's try to get the appdex high for this site
![image](https://user-images.githubusercontent.com/2479135/132378498-bb14884d-7ab6-414e-b1c5-367031b842db.png)


@seovalleygit

**Comment by rayrshah** [comment]
here is  the current site for comparison:

![image](https://user-images.githubusercontent.com/2479135/132378676-a57fd8b7-0179-4e63-8286-69363738d101.png)

**Comment by seovalleygit** [comment]
@rayrshah @adam-td @ajazmi 

Hello, I have optimized test site as per lighthouse suggestions.

![image](https://user-images.githubusercontent.com/86654942/132727959-53c5a830-b11f-4b61-98ac-3cefc0386a21.png)

**Comment by rayrshah** [comment]
@seovalleygit the appdex is very slightly better, I think there's more work to do.

**Comment by seovalleygit** [comment]
@rayrshah @ajazmi 
Improved performance score. Looking into appdex score if we can improve it. 
![image](https://user-images.githubusercontent.com/86654942/133250194-2a3e94f8-1115-45f2-9616-07177125434d.png)

**Comment by rayrshah** [comment]
OK this is  good enough for now thanks @seovalleygit
