### ISSUE TITLE
Fix Hero Image for Technology partner / match with current site

### ISSUE THREAD

**Issue by adam-td** [rayrshah/midisWP#66]
The hero image for https://test.midisgroup.com/technology-partners/ is blurred and at the wrong scale
WP
<img width="1280" alt="Screen Shot 2021-09-10 at 17 53 45" src="https://user-images.githubusercontent.com/87426372/132921652-9a09c6f7-84bd-447e-ab84-b8b7e1601588.png">

Current
<img width="1280" alt="Screen Shot 2021-09-10 at 17 54 22" src="https://user-images.githubusercontent.com/87426372/132921704-8f6501be-7ae6-4527-b1d4-ec4a4b4648a9.png">

**Comment by seovalleygit** [comment]
@adam-td @ajazmi Image updated as per current site.
