### ISSUE TITLE
Fonts are broken on test.midisgroup.com

### ISSUE THREAD

**Issue by rayrshah** [rayrshah/midisWP#68]
https://www.loom.com/share/6394c196ab4945b59654e872d12c935d

**Comment by rayrshah** [comment]
Helvetica Neue is  not showing up on computers that don't have it installed

**Comment by rayrshah** [comment]
@krishna711 @seovalleygit here are the missing fonts
[MTI-WebFonts-641136823.zip](https://github.com/rayrshah/midisWP/files/7209705/MTI-WebFonts-641136823.zip)
.

**Comment by seovalleygit** [comment]
@rayrshah Looking into this issue.

**Comment by seovalleygit** [comment]
@rayrshah It should be fixed now. Please check at your end. Thanks
