### ISSUE TITLE
Match publicly visible partners for FR Nos Partenaires page

### ISSUE THREAD

**Issue by adambard1** [rayrshah/midisWP#7]
- [x] Match the partners visible on the FR Nos Partenaires page
- [x] Enable independent draft selection for FR and EN partners on the back end
- [x] Do not publish draft content on the front end

The FR partners on the front end on the WordPress and Current site do not match. The EN partner logos are showing on the FR page,  but the directories for the EN and FR partners on the back end (and hence the front end) are different. There are multiple discrepancies but below just the top two lines are shared as an example.

e.g.
Current
FR Nos Partenaires
![Screen Shot 2021-06-11 at 11 51 31](https://user-images.githubusercontent.com/13530245/121714026-7836ae80-caab-11eb-8f50-af3b0747bee0.png)
WordPress
FR Nos Partenaires
![Screen Shot 2021-06-11 at 11 51 25](https://user-images.githubusercontent.com/13530245/121714055-7ec52600-caab-11eb-96d5-4a623b5a03f5.png)

**Comment by adambard1** [comment]
@ajazmi

**Comment by ajazmi** [comment]
@adambard1 Updated. Compared and matched with live FR page.
