### ISSUE TITLE
Pre-launch checks

### ISSUE THREAD

**Issue by rayrshah** [rayrshah/midisWP#70]
- [ ] Launch date Sept 30 proposed
- [ ] Documentation for EN and FR on adding and editing : News, Affiliates, Partners and editing content on existing pages / controlling pop-up  Mon, Sep 20 Ashutosh Verma Ashutosh V.
- [ ] live training for Roula and Jon Ray Shah Ray S.Schedule…
- [ ] Broken link check Note  Mon, Sep 20 Ashutosh Verma Ashutosh V.
- [ ] Load speed check Note  Tue, Sep 21 Ray Shah Ray S.
- [ ] Language navigation on News pages Note  Thu, Sep 23 Ashutosh Verma Ashutosh V.
- [ ] CookieBot config Note Ashutosh Verma Ashutosh V.Schedule…
- [ ] Update all stories until launch Note  Mon, Sep 20 - Thu, Sep 30 Ashutosh Verma Ashutosh V.
- [ ] Test Geo Sensitive content Ray Shah Ray S.Schedule…
- [ ] Fix broken fonts on test.midisgroup.com Note 1 Ashutosh Verma Ashutosh V. Nashit

**Comment by seovalleygit** [comment]
@rayrshah Uploading Documentation word doc here.
[Midis Group - Training Doc.docx](https://github.com/rayrshah/midisWP/files/7217171/Midis.Group.-.Training.Doc.docx)
 
For CookieBot Config: Please add test.midisgroup.com in cookiebot config. Cookie accept popup window should appear after adding subdomain in setting.

**Comment by seovalleygit** [comment]
@rayrshah 

Update

1. Documentation for EN and FR on adding and editing - Done
2. live training - This is already done in previous meetings
3. Broken link check - Link checked via broken link check plugin and those are identified and have been fixed.
4. Load speed check - Done in separate ticket.
**5. Language navigation on News pages - Can you please explain this as no details are given.**
6. CookieBot config - It will start working after live. 
7. Update all stories until launch - Latest Posts Updated till today.
8. Test Geo Sensitive content - This is already been tested. 
9. Fix broken fonts on test.midisgroup.com - Fixed. 

@rayrshah We also need to do following task before or after live.
1. Buy Licence for WPML plugin
2. Configure imgix plugins for WordPress. Current website also using it so same can be used with wordpress too. We will need credentials to configure this plugins. This is not mandatory but will be needed to automatically optimize images when uploaded.
