### ISSUE TITLE
Change directory name /affiliate/ to /affiliates/ to make links work

### ISSUE THREAD

**Issue by rayrshah** [rayrshah/midisWP#72]
Links from news pages to the affiliates don't work

e.g. ​https://test.midisgroup.com/better-mobile-online-banking-services-in-africa-with-hpe-synergy/

links to https://test.midisgroup.com/affiliates/selectium-ken-limited/

but there is  no /affiliates/ directory only an /affiliate/ one

on the old site the URL is :
https://www.midisgroup.com/affiliates/

Please make this consistent with the old site

**Comment by seovalleygit** [comment]
@rayrshah Updated affiliates link prefix from /affiliate/ to /affiliates/
