### ISSUE TITLE
fix fonts on firefox/mac

### ISSUE THREAD

**Issue by rayrshah** [rayrshah/midisWP#73]
![Screenshot 2021-10-05 at 15 20 32](https://user-images.githubusercontent.com/2479135/136093904-2adf771a-5aef-4ccf-a32f-1960125db263.png)

this is the browser: https://www.whatsmybrowser.org/b/CK4XG

**Comment by krishna711** [comment]
@rayrshah @ajazmi Font issue for firefox is fixed.
