### ISSUE TITLE
Create FR content for Tech partner side panel

### ISSUE THREAD

**Issue by adam-td** [rayrshah/midisWP#78]
Currently the side panel is in EN. For the FR site the content will be.

"Des acteurs du marché, allant de Apple, Hewlett Packard Enterprise (HPE), IBM et Google à Symantec, SAP et Dell Technologies, se basent sur notre expertise locale, technologique et commerciale, pour se développer avec un minimum de frais généraux et de risques à encourir."

- [ ] Replace EN content with this content for FR site

**Comment by krishna711** [comment]
@rayrshah @adam-td Content updated for FR. A box added in tech partners edit page to update sidebar content on both EN/FR page.

![image](https://user-images.githubusercontent.com/2379768/139653107-919cb936-90fd-4d58-a4e6-6a5e383eab0d.png)
