### ISSUE TITLE
Fix duplicate H2 subtitles are appearing on all HR News Articles – only one H2 subtitle should appear

### ISSUE THREAD

**Issue by adam-td** [rayrshah/midisWP#79]
- Subtitle (H2) duplication is happening, seemingly because the Excerpt field and Sub Title field on the back end appear to do the same thing.

![Screen Shot 2021-10-25 at 14 10 51](https://user-images.githubusercontent.com/87426372/138747821-ead01761-2240-44c2-b8a7-0eb65fcda80c.png)

<img width="926" alt="Screen Shot 2021-10-2
![Screen Shot 2021-10-25 at 14 10 51](https://user-images.githubusercontent.com/87426372/138747821-ead01761-2240-44c2-b8a7-0eb65fcda80c.png)
5 at 10 18 06" src="https://user-images.githubusercontent.com/87426372/138712726-11801814-58a7-4443-b0a6-5f7e4c070ad4.png">

<img width="966" alt="Screen Shot 2021-10-25 at 10 28 35" src="https://user-images.githubusercontent.com/87426372/138714903-af09071c-b758-4f80-b65c-c8da3b0ede95.png">

**Comment by krishna711** [comment]
@rayrshah @adam-td Updated to use only sub_title field for H2 content.
