### ISSUE TITLE
Affiliate Detail WordPress page design feedback

### ISSUE THREAD

**Issue by adambard1** [rayrshah/midisWP#8]
The [current WordPress page](https://midisgroup.thinkdesign.com/affiliate/abm-care-computer-services-dwc-llc/) differs from the Client approved design in a number of small ways. I will put them all on this ticket. They are also noted in Figma comments 115 through 122 on [this Figma page](https://www.figma.com/file/xfeXe5BWo5CbJ29BYbQKn1/Midis-UI-changes?node-id=693%3A746).

I have hidden the background so that the columns can be seen on the design. Though development may not be using those columns, they show how the alignment of elements was originally created.

The Brand Style Guide was completed before these pages were published, I have now updated the Brand Style Guide and the page design to reflect the typography styles. **Please match the typography size, weight, and color on Figma for the page content.**

- [ ] Main content and Affiliate business name container right-hand edge is Column 8
- [ ] Contact content container right hand edge is Column 6
- [ ] All typography and icons in the main content window except the Business name is now 606F7B
- [ ] H2s are the News Article format H2 1.25 rem medium weight
- [ ] Contact, Select Partners headings are 1.125 rem, medium weight
- [ ] Location 2, 3 etc. is 1 rem, medium weight

**Comment by adambard1** [comment]
@rayrshah @ajazmi

**Comment by ajazmi** [comment]
@adambard1 Updated as per design.

**Comment by adambard1** [comment]
Pls let us know when there are more DEtail pages to check than the sample page – some with multiple partners and locations would be good to see.

**Comment by seovalleygit** [comment]
@adambard1 @ajazmi 
Few more pages updated.

https://midisgroup.thinkdesign.com/affiliate/abm-care-computer-services-llc/
https://midisgroup.thinkdesign.com/affiliate/abm-care-lebanon-sal/
https://midisgroup.thinkdesign.com/affiliate/abm-care-limited-jordan/
https://midisgroup.thinkdesign.com/affiliate/advanced-business-computing-llc-abc-oman/
https://midisgroup.thinkdesign.com/affiliate/advanced-business-computing-w-l-l-abc-qatar/
https://midisgroup.thinkdesign.com/affiliate/advanced-financial-solutions-w-l-l/
https://midisgroup.thinkdesign.com/affiliate/aklaniat-technology-company-limited-llc-mindware-ksa/
https://midisgroup.thinkdesign.com/affiliate/apcom-ce-kft-hungary/
https://midisgroup.thinkdesign.com/affiliate/apcom-czech-s-r-o/

**Comment by seovalleygit** [comment]
@adambard1 @ajazmi Meta tags and content updated on all affiliate pages in excel sheet.
