### ISSUE TITLE
Fix double H1s on HR News Article pages: Hero and Article both contain an H1

### ISSUE THREAD

**Issue by adam-td** [rayrshah/midisWP#80]
- [ ] When clicking through to an HR news article the Hero content H1 should become an H2
<img width="963" alt="Screen Shot 2021-10-25 at 10 23 18" src="https://user-images.githubusercontent.com/87426372/138714318-328386a1-70b4-4df3-ad57-fa3bfe4c9066.png">

**Comment by krishna711** [comment]
@rayrshah @adam-td hero content H1 updated to H2.
