### ISSUE TITLE
Add Language change header for HR News Articles

### ISSUE THREAD

**Issue by adam-td** [rayrshah/midisWP#81]
There is no language change header on any [HR News articles page](https://test.midisgroup.com/career/building-on-excellence-interview-with-elie-oueiss-director-of-hr-midis-group/)(s). Add it above the header menu.
(this is also missing on the current site, but is needed before deployment)
<img width="1280" alt="Screen Shot 2021-10-25 at 14 03 47" src="https://user-images.githubusercontent.com/87426372/138747308-13e2c53c-614a-49d1-ad80-9d9f7b60e788.png">

**Comment by krishna711** [comment]
@rayrshah @adam-td enabled for news and hr news. It will not appear if post translation not present.
