### ISSUE TITLE
Enable all elements of HR News articles to be duplicated into FR/EN

### ISSUE THREAD

**Issue by adam-td** [rayrshah/midisWP#82]
When creating a Duplicate of an EN HR News article, 3 elements in the original story did not get duplicated.

- [ ] Post Data (Country) should be duplicated
- [ ] Featured Image should be duplicated
- [ ] Sub Title should be duplicated (except also did not duplicate but we will remove this item from the page)

**Comment by krishna711** [comment]
@rayrshah @adam-td @ajazmi 
Option for copying post content only.
![image](https://user-images.githubusercontent.com/2379768/140026261-d45df543-d048-40fe-85cc-91ef2a3b9c7e.png)

Option for duplicating post with all the meta data.

![image](https://user-images.githubusercontent.com/2379768/140027150-bbc3a549-f4fb-418b-a1c0-6e49d0c382aa.png)

**Comment by adam-td** [comment]
Add to documentation please

**Comment by adam-td** [comment]
Documentation should indicate that users should not select the + button under the Translate column if they want all data copied over, but must click the Duplicate button.

**Comment by krishna711** [comment]
@adam-td @rayrshah Updated document #48
