### ISSUE TITLE
Fix Category selection/Category sub-menu filter on the News Page

### ISSUE THREAD

**Issue by adam-td** [rayrshah/midisWP#85]
- The Article/Announcement/Awards selection for posts on the [News Page](https://test.midisgroup.com/news/) does not filter articles – all posts appear on all pages.

- Selecting one or another of the checkboxes on the CMS has no effect.

- [ ] Enable the CMS selection of posts as Announcements, Article, Award, to be reflected on the site when selecting that category from the News page sub-menu
- [ ] Make sure for FR selection as well (Articles, Annonces, Prix)
<img width="853" alt="Screen Shot 2021-10-25 at 14 43 48" src="https://user-images.githubusercontent.com/87426372/138753249-b2be0fc7-259f-468e-bc3e-9d1c7738cad9.png">

**Comment by krishna711** [comment]
@rayrshah @adam-td @ajazmi Category filters updated on both EN and FR pages.
