### ISSUE TITLE
Enable H2 Subtitles on News Posts CMS page to work the same way as the HR News CMS page

### ISSUE THREAD

**Issue by adam-td** [rayrshah/midisWP#86]
**Either**

- [ ] Retitle the Excerpt field in the Posts CMS to "Subtitle"

**OR**
- [ ] Add the Subtitle, to operate as it does in the HR News CMS page
- [ ] Remove the Excerpts field from the CMS page

This is the field to change/replace

<img width="794" alt="Screen Shot 2021-11-02 at 12 37 26" src="https://user-images.githubusercontent.com/87426372/139907593-2e76f90c-5ae6-4f3c-9c27-4359c8210f9f.png">

**Comment by krishna711** [comment]
@adam-td @rayrshah @ajazmi Excerpt field is replaced with subtitle field.
