### ISSUE TITLE
Line height for Company name on Affiliate Detail pages to be 1.125 em as per current site

### ISSUE THREAD

**Issue by adam-td** [rayrshah/midisWP#91]
- [ ] on test.midis site for the Affliate detail page, the lh for the company title (h2 class) is not being allowed. Enable the 1.125 lh

![Screen Shot 2021-10-25 at 17 26 18](https://user-images.githubusercontent.com/87426372/138773448-2cd28005-e775-4365-87a2-e7a9e8927fa4.png)

Current site...
![Screen Shot 2021-10-25 at 17 20 55](https://user-images.githubusercontent.com/87426372/138772881-02d5056c-419a-429c-a79c-dffbc67f9e19.png)

**Comment by krishna711** [comment]
@adam-td  @rayrshah Updated as per live site.
