### ISSUE TITLE
Affiliate detail pages missing H2 class headings in the main content

### ISSUE THREAD

**Issue by adam-td** [rayrshah/midisWP#92]
- The content is designed to provide 2 H2 headings in the main content window. These are currently text-xl class.

![Screen Shot 2021-10-25 at 17 36 20](https://user-images.githubusercontent.com/87426372/138774895-f4374287-c854-4b63-b331-543464c4b052.png)

- [ ] Amend all Affiliate detail pages to follow the heading rules in the [SEO document] with H2s in the main content (https://docs.google.com/spreadsheets/d/1b3vCGZiZttIEaDjsmkMZZKmVH6-PKT5q-R8sJyDugoE/edit#gid=0)

**Comment by krishna711** [comment]
@adam-td @rayrshah Hello Adam, I updated h2 on affiliate https://test.midisgroup.com/affiliates/abm-care-computer-services-dwc-llc/ here. I change it to h2 and kept text-xl class same. Please do check and confirm if it is correct. I will update on other affiliates once confirmed.

**Comment by adam-td** [comment]
Yes, that is looking right except for [in the design (this one uses Helvetica Neue)](https://www.figma.com/file/oH0sJGfswfMBtm4aenKOl4/Midis-UI-changes-%E2%80%93-Client-only?node-id=721%3A695)

- [ ] the H1s are 1.5rem not 1.875 rem.
- [ ] the H2s are gray 606F7B

Please update all.

**Comment by krishna711** [comment]
@adam-td Updated.
