### ISSUE TITLE
Add documentation on requiring a thumbnail for employees to feature on Joining the Group carousel

### ISSUE THREAD

**Issue by adam-td** [rayrshah/midisWP#95]
[This test employee](https://test.midisgroup.com/wp/wp-admin/post.php?post=9316&action=edit&lang=en) [and their quote](https://test.midisgroup.com/wp/wp-admin/post.php?post=9317&action=edit&lang=en) is visible in the Working with Us carousel and in the Sidebar (although how do we preview what that sidebar will look like?) as selected on the checkboxes. But it does not appear in the Joining the Group carousel, though selected.

- [x] Enable the employee to appear in the Joining the Group Carousel when that Show on Pages checkbox is selected.

**Comment by krishna711** [comment]
@adam-td @rayrshah Joining the Group Carousel limit increase from 5-10.  Thumb square image need to add to appear properly in join the group circle. 

![image](https://user-images.githubusercontent.com/2379768/139632298-4217475e-ceb4-41c5-8860-b16d6c8dabca.png)

![image](https://user-images.githubusercontent.com/2379768/139632382-77b800c5-5dd8-4231-94a6-390f0cca7524.png)

**Comment by adam-td** [comment]
OK. Thanks @krishna711 I did not know we had to create a thumbnail. Is there a way for the CMS to automatically load a thumbnail from any selected employee image?

**Comment by adam-td** [comment]
- [ ] Please create a section on Employee quotes in the Documentation

**Comment by krishna711** [comment]
@adam-td @rayrshah @ajazmi Yes, It is possible to load from selected employee thumbnail but it is special carousel. It will be good to use separate image for navigation header image so only employee face can be focused. If we use employee image some employee face in the image may not be centered thus it will cut off in the circle.

**Comment by adam-td** [comment]
- [ ] Provide instruction that section of the cms that a 100x100 thumbnail of the employee should be created

**Comment by krishna711** [comment]
@adam-td @rayrshah Updated document #48
