### ISSUE TITLE
Enable Technology partners preview to show Featured Image

### ISSUE THREAD

**Issue by adam-td** [rayrshah/midisWP#97]
Uploading a new image to a published technology partner and clicking preview takes you to the Affiliate representing the partner, which does not show partner logo images image (no image would appear on that page).

- [ ] When uploading an image for a technology partner, the preview should be of the Technology Partners main page, where all the logos are shown.

**Comment by krishna711** [comment]
@adam-td @rayrshah @ajazmi Preview link for partner page updated to technology partners main page.
